# Generated by Django 3.2.7 on 2021-09-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
